export default {
  login: "Dovtutis",
  id: 70949854,
  node_id: "MDQ6VXNlcjcwOTQ5ODU0",
  avatar_url: "https://avatars.githubusercontent.com/u/70949854?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Dovtutis",
  html_url: "https://github.com/Dovtutis",
  followers_url: "https://api.github.com/users/Dovtutis/followers",
  following_url: "https://api.github.com/users/Dovtutis/following{/other_user}",
  gists_url: "https://api.github.com/users/Dovtutis/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Dovtutis/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Dovtutis/subscriptions",
  organizations_url: "https://api.github.com/users/Dovtutis/orgs",
  repos_url: "https://api.github.com/users/Dovtutis/repos",
  events_url: "https://api.github.com/users/Dovtutis/events{/privacy}",
  received_events_url: "https://api.github.com/users/Dovtutis/received_events",
  type: "User",
  site_admin: false,
  name: "Dovydas",
  company: "-",
  blog: "https://dovtutisportfolio.netlify.app/",
  location: "Vilnius",
  email: null,
  hireable: null,
  bio: "Full-stack junior WEB developer.",
  twitter_username: "Dovtutis",
  public_repos: 46,
  public_gists: 0,
  followers: 3,
  following: 4,
  created_at: "2020-09-08T10:50:11Z",
  updated_at: "2021-10-26T15:24:04Z",
};
