export default [
  {
    login: "zzzarius",
    id: 2293236,
    node_id: "MDQ6VXNlcjIyOTMyMzY=",
    avatar_url: "https://avatars.githubusercontent.com/u/2293236?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/zzzarius",
    html_url: "https://github.com/zzzarius",
    followers_url: "https://api.github.com/users/zzzarius/followers",
    following_url:
      "https://api.github.com/users/zzzarius/following{/other_user}",
    gists_url: "https://api.github.com/users/zzzarius/gists{/gist_id}",
    starred_url: "https://api.github.com/users/zzzarius/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/zzzarius/subscriptions",
    organizations_url: "https://api.github.com/users/zzzarius/orgs",
    repos_url: "https://api.github.com/users/zzzarius/repos",
    events_url: "https://api.github.com/users/zzzarius/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/zzzarius/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "1Laura",
    id: 35330958,
    node_id: "MDQ6VXNlcjM1MzMwOTU4",
    avatar_url: "https://avatars.githubusercontent.com/u/35330958?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/1Laura",
    html_url: "https://github.com/1Laura",
    followers_url: "https://api.github.com/users/1Laura/followers",
    following_url: "https://api.github.com/users/1Laura/following{/other_user}",
    gists_url: "https://api.github.com/users/1Laura/gists{/gist_id}",
    starred_url: "https://api.github.com/users/1Laura/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/1Laura/subscriptions",
    organizations_url: "https://api.github.com/users/1Laura/orgs",
    repos_url: "https://api.github.com/users/1Laura/repos",
    events_url: "https://api.github.com/users/1Laura/events{/privacy}",
    received_events_url: "https://api.github.com/users/1Laura/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ChopinNocturnes",
    id: 88656837,
    node_id: "MDQ6VXNlcjg4NjU2ODM3",
    avatar_url: "https://avatars.githubusercontent.com/u/88656837?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ChopinNocturnes",
    html_url: "https://github.com/ChopinNocturnes",
    followers_url: "https://api.github.com/users/ChopinNocturnes/followers",
    following_url:
      "https://api.github.com/users/ChopinNocturnes/following{/other_user}",
    gists_url: "https://api.github.com/users/ChopinNocturnes/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/ChopinNocturnes/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/ChopinNocturnes/subscriptions",
    organizations_url: "https://api.github.com/users/ChopinNocturnes/orgs",
    repos_url: "https://api.github.com/users/ChopinNocturnes/repos",
    events_url: "https://api.github.com/users/ChopinNocturnes/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ChopinNocturnes/received_events",
    type: "User",
    site_admin: false,
  },
];
